[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "chromium", "glib", "nss", "freetype", "harfbuzz", "ca-certificates"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
